services:
  metabase:
    image: metabase/metabase:latest
    container_name: afc_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${DATABASE_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${DATABASE_USER}
      MB_DB_PASS: ${DATABASE_PASSWORD}
      MB_DB_HOST: ${DATABASE_HOST}

volumes:
  postgres_data: